apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

commonLabels:
  tier: frontend
  app.kubernetes.io/name: nginx
  app.kubernetes.io/component: proxy  

configMapGenerator:
- name: nginx-config
  files:
    - config/nginx.conf
