apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/name: postgresql
spec:
  selector:
    app.kubernetes.io/name: postgresql
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  
