apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
        name: redis
    spec:    
      containers:
        - env:
          - name: TZ
            value: US/Eastern
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 6379
            timeoutSeconds: 1
          name: redis
          ports:
          - containerPort: 6379
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - test "$(redis-cli -h 127.0.0.1 ping)" == "PONG"
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          image: image-registry.openshift-image-registry.svc:5000/openshift/redis:5-el8
          volumeMounts:
          - mountPath: /var/lib/redis/data
            name: redis-data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis
