apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- pvc.yaml

commonLabels:
  tier: middleware
  app.kubernetes.io/name: redis
  app.kubernetes.io/component: queue
 
