apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../bases/components/apps/app-name
- ../../../bases/components/apps/nginx
- ../../../bases/components/apps/postgresql
# - ../../../bases/components/tls
# - ../../../bases/components/apps/redis

commonAnnotations:
  owner: "group-name"
  owner-email: group-email

commonLabels:
  app.kubernetes.io/part-of: app-name
  app.kubernetes.io/managed-by: kustomize
