apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployments.yaml
- service.yaml
- pvc.yaml

# Add any add'l environment variables your app will need *in all environments*.
configMapGenerator:
  - name: app-server-config
    literals:
      - DISABLE_MIGRATE=1
      - TIMEZONE=America/New_York
      - FOO="bar"

  # Migration script will be mounted inside the initContainer and called every 
  # time a new deployment happens.
  - name: migration-script
    files:
      - migrate.sh

# Generate the base set of secrets here. You can add environment-specific secrets in 
# the environment kustomization files (e.g., environments/overlays/dev/kustomization.yaml)
secretGenerator:
  - name: app-server-secrets
    type: Opaque
    envs:
      - secrets.env
