apiVersion: v1
kind: Service
metadata:
  labels:
    tier: frontend
    app.kubernetes.io/name: django
    app.kubernetes.io/component: app-server
  name: django
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    tier: frontend
    app.kubernetes.io/name: django
    app.kubernetes.io/component: app-server

